import type { AcademicProfile, AcademicSubject } from "./types";

/**
 * Approved faculty records.
 *
 * Content authority: Rank_Sarthi_Faculty_Profile_Master_for_Lovable.docx.
 * `shortProfile` is used for About-page cards and compact contexts.
 * `detailedProfile` is the full cleaned academic profile rendered only on the
 * individual profile page. Claims still awaiting evidence stay in
 * `claimsRequiringEvidence`, which is internal and never rendered.
 * `verificationStatus` is internal state and is never displayed publicly.
 */
const partial = "PARTIALLY_VERIFIED" as const;

export const academicProfiles: AcademicProfile[] = [
  {
    id: "sachin-garg",
    slug: "sachin-garg",
    name: "Sachin Garg",
    title: "Senior Mathematics Faculty",
    subject: "Mathematics",
    role: "Senior Academic Contributor — Mathematics",
    shortProfile:
      "Sachin Garg is a Senior Mathematics Faculty member and academic contributor focused on building structured, progressively graded Mathematics learning resources. His contribution emphasises conceptual clarity, logical progression, analytical reasoning and systematic problem-solving.",
    detailedProfile: [
      "Sachin Garg is a senior academic contributor in Mathematics whose work focuses on the development of a comprehensive, scientifically structured and progressively graded body of Mathematics content. His contribution supports Rank Sarthi’s objective of giving students a consistent and intellectually rigorous pathway towards mathematical understanding and mastery.",
      "His academic work centres on the creation, organisation, refinement and continuous improvement of Mathematics learning resources. Each topic is treated as part of a longer learning sequence rather than an isolated chapter, so that definitions, standard results, techniques and applications are introduced in an order a learner can actually build on.",
      "Conceptual clarity is the first requirement in his approach. Before a student is asked to solve at competitive difficulty, the underlying idea, its conditions of validity and its typical failure cases are made explicit. This reduces the pattern-memorisation habit that tends to collapse when an examination changes the surface form of a familiar question.",
      "Analytical reasoning and systematic problem-solving form the second layer. Problems are graded so that a learner moves from direct application, through multi-step combinations of ideas, to problems that require selecting a method rather than executing a given one. The intent is transferable method-selection skill, not exposure to a longer list of solved questions.",
      "He also contributes to the structuring of Mathematics coverage across the syllabus: how units are sequenced, where foundational skills need reinforcement before a harder unit begins, and where a topic requires separate treatment for different examinations rather than a single shared explanation.",
      "As a senior contributor to the academic framework, Sachin brings subject depth and academic discipline to Mathematics content development, helping learners strengthen conceptual foundations, mathematical thinking, accuracy and confidence over time.",
    ],
    academicFocus: [
      "Structuring Mathematics coverage into a coherent, progressively graded learning sequence",
      "Conceptual clarity before competitive-level application",
      "Analytical reasoning and method selection in multi-step problems",
      "Accuracy, consistency and academic discipline across Mathematics content",
    ],
    expertise: [
      "Mathematics",
      "Concept Development",
      "Analytical Reasoning",
      "Problem Solving",
      "Curriculum Structuring",
      "Progressively Graded Learning",
    ],
    examScope: ["JEE Main Mathematics", "JEE Advanced Mathematics"],
    contribution: [
      "Development and continuous refinement of Rank Sarthi Mathematics subject content.",
      "Structuring of topic sequences and graded problem sets so difficulty rises with learner readiness.",
      "Academic accuracy checks on Mathematics explanations, standard results and worked solutions.",
    ],
    reviewAreas: ["Mathematics", "JEE Main Mathematics", "JEE Advanced Mathematics", "Curriculum Structuring", "Problem Solving"],
    relatedPages: ["/jee/syllabus/mathematics", "/jee/mathematics", "/jee/syllabus"],
    verificationStatus: partial,
    photo: "/faculty/sachin-garg-senior-mathematics-faculty-rank-sarthi.webp",
    photoFilename: "sachin-garg-senior-mathematics-faculty-rank-sarthi.webp",
    imageAlt: "Sachin Garg, Senior Mathematics Faculty at Rank Sarthi",
    initials: "SG",
    claimsRequiringEvidence: [
      "Exact exams taught or reviewed",
      "Education or qualification",
      "Teaching experience",
      "Previous institutions",
      "LinkedIn",
      "Professional email",
    ],
  },
  {
    id: "gandharva-saxena",
    slug: "gandharva-saxena",
    name: "Gandharva Saxena",
    title: "Senior Physics Faculty",
    subject: "Physics",
    role: "Senior Academic Contributor — Physics",
    shortProfile:
      "Gandharva Saxena is a Senior Physics Faculty member and academic contributor focused on creating rigorous, conceptually strong and progressively structured Physics learning resources, emphasising scientific reasoning and the systematic application of fundamental principles.",
    detailedProfile: [
      "Gandharva Saxena is a senior academic contributor in Physics, bringing subject expertise and a strong commitment to scientifically rigorous, conceptually clear and student-focused learning resources.",
      "His contribution includes the creation, structuring, refinement and continuous enrichment of Physics content so that students progress through a coherent learning sequence instead of a set of disconnected chapters. Mechanics, thermal physics, electromagnetism, optics and modern physics are treated as a connected body of principles that reappear in new contexts.",
      "His academic approach emphasises conceptual understanding before formula application. A physical situation is first described in terms of the principle that governs it — conservation, field behaviour, equilibrium, symmetry — and only then reduced to the equation used to solve it. This makes the relationship between assumptions and results visible to the learner.",
      "Analytical thinking and problem-solving ability are developed through graded problem work: representing a situation correctly, choosing the governing principle, carrying out the algebra with dimensional discipline, then checking the result for physical plausibility. Unit consistency, limiting cases and order-of-magnitude checks are treated as part of solving, not as optional extras.",
      "He also contributes to the scientific quality and internal consistency of Physics explanations across the syllabus, ensuring notation, sign conventions and definitions remain uniform so that a learner reading two related topics is not forced to reconcile two different conventions.",
      "Within the broader academic framework, Gandharva supports the progression from foundational concepts to advanced understanding, with particular attention to depth, accuracy and clarity in competitive-examination Physics.",
    ],
    academicFocus: [
      "Conceptual Physics built on governing principles rather than formula recall",
      "Graded analytical problem-solving with dimensional and limiting-case discipline",
      "Scientific accuracy and notation consistency across Physics content",
      "Coherent progression from foundational to advanced Physics",
    ],
    expertise: [
      "Physics",
      "Conceptual Physics",
      "Analytical Thinking",
      "Problem Solving",
      "Scientific Reasoning",
      "Curriculum Development",
    ],
    examScope: ["JEE Main Physics", "JEE Advanced Physics", "NEET Physics"],
    contribution: [
      "Creation and enrichment of Rank Sarthi Physics subject content.",
      "Scientific-accuracy and consistency work across Physics explanations and derivations.",
      "Development of graded Physics problem progressions from foundational to advanced level.",
    ],
    reviewAreas: ["Physics", "JEE Physics", "NEET Physics", "Conceptual Physics", "Scientific Reasoning"],
    relatedPages: ["/jee/syllabus/physics", "/jee/physics", "/neet/syllabus/physics", "/neet/physics"],
    verificationStatus: partial,
    photo: "/faculty/gandharva-saxena-senior-physics-faculty-rank-sarthi.webp",
    photoFilename: "gandharva-saxena-senior-physics-faculty-rank-sarthi.webp",
    imageAlt: "Gandharva Saxena, Senior Physics Faculty at Rank Sarthi",
    initials: "GS",
    claimsRequiringEvidence: [
      "Education or qualification",
      "Teaching experience",
      "Previous institutions",
      "Exact exams taught or reviewed",
      "LinkedIn",
      "Professional email",
    ],
  },
  {
    id: "adarsh-kumar",
    education: "Chaudhary Charan Singh University",
    slug: "adarsh-kumar",
    name: "Adarsh Kumar",
    title: "Senior Chemistry Faculty",
    subject: "Chemistry",
    role: "Senior Chemistry Faculty",
    shortProfile:
      "Adarsh Kumar is a senior Chemistry educator and academic architect working across competitive-exam Chemistry, curriculum design and structured assessment. His approach combines subject expertise with systematic problem-solving and performance-oriented learning frameworks for JEE and NEET aspirants.",
    detailedProfile: [
      "Adarsh Kumar is a senior Chemistry educator whose academic work spans Chemistry subject expertise, curriculum design, structured assessment and the academic architecture that holds a large body of learning content together.",
      "His Chemistry education work covers the full subject: physical chemistry, where quantitative reasoning and unit discipline dominate; inorganic chemistry, where periodic trends and bonding models explain observed behaviour; and organic chemistry, where mechanism and electronic structure explain reactivity. The emphasis is on reasoning from principle rather than memorising outcomes.",
      "In competitive-exam learning, his approach is to separate what the examination actually assesses from what merely looks difficult. Concepts are introduced with their scope boundaries stated, so a learner understands both what a model explains and where it stops being valid — a distinction that matters when JEE and NEET frame the same topic at different depths.",
      "Curriculum design is a core part of his contribution. He works on how Chemistry units are sequenced, which prerequisites must be secure before a harder unit begins, and how a single topic should be presented differently for different examinations without duplicating or contradicting the shared academic core.",
      "Structured assessment design is the second pillar. Question sets are built to diagnose rather than only to score: distinguishing a conceptual gap from a calculation error, an unfamiliar representation from an unlearned principle, and a reading mistake from a reasoning mistake. Assessment output is intended to be actionable for the learner.",
      "Rigorous problem-solving runs through both. Problems are graded from direct application to multi-concept synthesis, with explicit attention to the method-selection step that separates a prepared candidate from a well-read one, and to the accuracy habits that decide outcomes under timed conditions.",
      "His academic-architecture work concerns the systems around the content: consistent terminology, coherent topic hierarchies, traceable official-source references and repeatable review structures, so that Chemistry content stays accurate and internally consistent as it grows.",
      "His wider interests extend to scientific research and technology-enabled education, and at Rank Sarthi these inform how Chemistry content, assessment and learning progression are structured and delivered.",
    ],
    academicFocus: [
      "Chemistry reasoning across physical, inorganic and organic domains",
      "Exam-specific scope boundaries for JEE and NEET Chemistry",
      "Curriculum design and prerequisite sequencing",
      "Diagnostic assessment design and rigorous graded problem-solving",
      "Academic architecture: terminology, hierarchy and source traceability",
    ],
    expertise: [
      "Chemistry",
      "JEE Chemistry",
      "NEET Chemistry",
      "Curriculum Design",
      "Assessment Design",
      "Academic Architecture",
      "Scientific Research",
    ],
    examScope: ["JEE Main Chemistry", "JEE Advanced Chemistry", "NEET Chemistry"],
    contribution: [
      "Chemistry curriculum design and unit sequencing across JEE and NEET content.",
      "Structured, diagnostic assessment design for Chemistry question sets.",
      "Graded problem-solving frameworks from direct application to multi-concept synthesis.",
      "Academic architecture work on terminology consistency and official-source traceability.",
    ],
    reviewAreas: [
      "Chemistry",
      "JEE Chemistry",
      "NEET Chemistry",
      "Curriculum Design",
      "Assessment Design",
      "Academic Architecture",
    ],
    relatedPages: ["/jee/syllabus/chemistry", "/jee/chemistry", "/neet/syllabus/chemistry", "/neet/chemistry"],
    verificationStatus: partial,
    photo: "/faculty/adarsh-kumar-senior-chemistry-faculty-rank-sarthi.webp",
    photoFilename: "adarsh-kumar-senior-chemistry-faculty-rank-sarthi.webp",
    imageAlt: "Adarsh Kumar, Senior Chemistry Faculty at Rank Sarthi",
    initials: "AK",
    claimsRequiringEvidence: [
      "Exact public title",
      "FIITJEE tenure",
      "Head of Department role",
      "PhD research status",
      "Air Elixir role",
      "Patents",
      "VMedico or Rank UP roles",
      "Years of experience",
      "LinkedIn",
      "Professional email",
    ],
  },
  {
    id: "vinod-kumar",
    slug: "vinod-kumar",
    name: "Vinod Kumar",
    title: "Senior Chemistry Faculty",
    subject: "Chemistry",
    role: "Senior Academic Contributor — Chemistry",
    shortProfile:
      "Vinod Kumar is a Senior Chemistry Faculty member working in competitive-exam education and academic content development. His work strengthens conceptual foundations, analytical ability and problem-solving in Chemistry for JEE, NEET and other competitive examinations.",
    detailedProfile: [
      "Vinod Kumar is a senior Chemistry academic contributor whose work focuses on concept clarity, scientific accuracy, progressively graded content and competitive problem-solving.",
      "His contribution follows the full learner journey in Chemistry: securing fundamentals first, then building the conceptual depth, analytical ability and problem-solving required by JEE, NEET and other competitive examinations. Each stage assumes only what the previous stage established.",
      "In practice this means explanations that make the governing idea explicit before the shortcut. Stoichiometric reasoning, equilibrium behaviour, periodic trends and reaction mechanisms are presented as consequences of a smaller set of principles, so a learner can reconstruct a result rather than recall it.",
      "Scientific accuracy is treated as non-negotiable. Definitions, units, conventions and the conditions attached to a standard result are stated precisely, because Chemistry questions at competitive level frequently test exactly the condition a loose explanation omits.",
      "His academic content development work covers progressively structured resources: topic explanations, worked examples and graded practice sequences arranged so difficulty increases only after the prerequisite reasoning is in place.",
      "Within Rank Sarthi, his positioning is as a senior Chemistry academic contributor focused on concept clarity, scientific accuracy, graded content and the problem-solving ability that competitive Chemistry demands.",
    ],
    academicFocus: [
      "Concept clarity from Chemistry fundamentals to competitive depth",
      "Scientific accuracy in definitions, units and conditions of validity",
      "Progressively graded Chemistry content and practice sequences",
      "Analytical problem-solving for JEE and NEET Chemistry",
    ],
    expertise: [
      "Chemistry",
      "JEE Chemistry",
      "NEET Chemistry",
      "Academic Content Development",
      "Competitive Exam Preparation",
      "Problem Solving",
    ],
    examScope: ["JEE Chemistry", "NEET Chemistry"],
    contribution: [
      "Development of progressively structured Chemistry learning resources.",
      "Concept-clarity and scientific-accuracy work across Chemistry explanations.",
      "Graded Chemistry practice sequences for competitive preparation.",
    ],
    reviewAreas: ["Chemistry", "JEE Chemistry", "NEET Chemistry", "Academic Content Development", "Problem Solving"],
    relatedPages: ["/neet/syllabus/chemistry", "/neet/chemistry", "/jee/syllabus/chemistry", "/jee/chemistry"],
    verificationStatus: partial,
    photo: null,
    photoFilename: null,
    imageAlt: null,
    initials: "VK",
    claimsRequiringEvidence: [
      "Years of experience",
      "Previous institutions",
      "Books or authorship",
      "Student outcomes",
      "LinkedIn",
      "Professional email",
    ],
  },
  {
    id: "ashwin-m",
    slug: "ashwin-m",
    name: "Ashwin M.",
    title: "Senior Physics Faculty",
    subject: "Physics",
    role: "Senior Academic Contributor — Physics",
    shortProfile:
      "Ashwin M. is a Senior Physics Faculty member whose teaching approach centres on making complex Physics intuitive, conceptually clear and analytically rigorous, spanning competitive-exam Physics, structured problem-solving and progressively graded learning resources.",
    detailedProfile: [
      "Ashwin M. is a Physics educator whose academic approach emphasises conceptual understanding, intuitive explanation and structured reasoning rather than mechanical learning.",
      "His work centres on making complex Physics intuitive without making it imprecise. A topic is introduced through the physical picture — what is changing, what is conserved, what constrains the system — and the mathematics is then attached to that picture rather than presented as the starting point.",
      "He has guided students preparing for advanced school-level and competitive science examinations, and his content reflects that range: the same principle is developed at the depth each examination requires, with the difference in depth made explicit instead of blurred.",
      "Structured reasoning is the core method. Problems are approached as a sequence of decisions — represent the situation, identify the governing law, reduce to solvable form, solve, then validate against limiting cases and dimensions. Learners are trained on the decision sequence, which transfers, rather than on remembered solutions, which do not.",
      "His contribution to learning resources focuses on progressive grading: foundational reasoning, then standard competitive application, then problems requiring several principles to be combined. Each stage is scientifically accurate and self-consistent so a learner is never asked to unlearn a simplification later.",
      "At Rank Sarthi, his profile focuses on Physics pedagogy, conceptual clarity, competitive problem-solving and the development of scientifically accurate, progressively graded Physics learning resources.",
    ],
    academicFocus: [
      "Intuitive but precise conceptual Physics",
      "Structured reasoning sequences for problem-solving",
      "Exam-appropriate depth for JEE and NEET Physics",
      "Progressively graded, scientifically accurate Physics resources",
    ],
    expertise: [
      "Physics",
      "JEE Physics",
      "NEET Physics",
      "Conceptual Learning",
      "Analytical Problem Solving",
      "Competitive Exam Physics",
    ],
    examScope: ["JEE Main Physics", "JEE Advanced Physics", "NEET Physics"],
    contribution: [
      "Physics pedagogy and conceptual-clarity work across Rank Sarthi Physics content.",
      "Development of structured problem-solving sequences for competitive Physics.",
      "Progressive grading of Physics learning resources from foundational to advanced level.",
    ],
    reviewAreas: ["Physics", "JEE Physics", "NEET Physics", "Conceptual Learning", "Competitive Exam Physics"],
    relatedPages: ["/jee/syllabus/physics", "/jee/physics", "/neet/syllabus/physics", "/neet/physics"],
    verificationStatus: partial,
    photo: "/faculty/ashwin-m-senior-physics-faculty-rank-sarthi.webp",
    photoFilename: "ashwin-m-senior-physics-faculty-rank-sarthi.webp",
    imageAlt: "Ashwin M., Senior Physics Faculty at Rank Sarthi",
    initials: "AM",
    claimsRequiringEvidence: [
      "Final public name",
      "IIT Madras qualification",
      "Teaching since 2012",
      "Phyritual Edu",
      "Student outcomes",
      "LinkedIn",
      "Professional email",
    ],
  },
  {
    id: "ashutosh-pande",
    slug: "ashutosh-pande",
    name: "Ashutosh Pande",
    title: "Senior Mathematics Faculty",
    subject: "Mathematics",
    role: "Senior Mathematics Faculty / Academic Consultant",
    shortProfile:
      "Ashutosh Pande is a Senior Mathematics Faculty member and academic consultant specialising in JEE Main and JEE Advanced Mathematics, focused on concept clarity, multi-step reasoning, structured problem-solving and curriculum design.",
    detailedProfile: [
      "Ashutosh Pande is a Mathematics educator and Senior Academic Consultant specialising in curriculum design and mentorship for JEE Main and JEE Advanced Mathematics.",
      "His academic approach centres on concept clarity, systematic problem-solving, multi-step reasoning, analytical agility, speed-accuracy optimisation and examination temperament. These are treated as trainable components rather than traits: each has its own practice structure and its own diagnostic signal.",
      "Multi-step reasoning is the distinguishing focus of his work. Advanced Mathematics questions rarely fail on a single technique; they fail at the joins between techniques. His content therefore emphasises problems where the difficulty lies in choosing and sequencing methods — algebraic manipulation into calculus, coordinate reformulation into vector reasoning, and similar transitions.",
      "Curriculum design and content curation form a second strand: deciding what belongs at each stage of preparation, what depth a topic requires for Main as against Advanced, and how a topic should be revisited later at higher difficulty instead of being taught once at maximum depth.",
      "He also works on question-bank design, assessment blueprints and performance analytics — structuring practice so that results indicate where a learner's method selection, algebraic accuracy or time allocation is failing, rather than only producing a score.",
      "Speed-accuracy optimisation completes the approach: identifying the routine steps that should become automatic, so that limited examination time is spent on the reasoning that actually carries marks.",
      "For Rank Sarthi, his profile centres on JEE Mathematics, curriculum design, analytical reasoning and advanced problem-solving.",
    ],
    academicFocus: [
      "JEE Main and JEE Advanced Mathematics depth differentiation",
      "Multi-step reasoning and method sequencing",
      "Curriculum design, content curation and assessment blueprints",
      "Speed-accuracy optimisation and examination temperament",
    ],
    expertise: [
      "Mathematics",
      "JEE Main Mathematics",
      "JEE Advanced Mathematics",
      "Curriculum Design",
      "Multi-Step Reasoning",
      "Problem Solving",
      "Assessment Planning",
    ],
    examScope: ["JEE Main Mathematics", "JEE Advanced Mathematics"],
    contribution: [
      "Curriculum design and staged depth planning for JEE Mathematics content.",
      "Question-bank design and assessment blueprints for Mathematics practice.",
      "Advanced multi-step problem-solving progressions and accuracy-focused practice structures.",
    ],
    reviewAreas: [
      "Mathematics",
      "JEE Main Mathematics",
      "JEE Advanced Mathematics",
      "Curriculum Design",
      "Assessment Planning",
    ],
    relatedPages: ["/jee/jee-advanced/syllabus", "/jee/syllabus/mathematics", "/jee/mathematics"],
    verificationStatus: partial,
    photo: "/faculty/ashutosh-pande-senior-mathematics-faculty-rank-sarthi.webp",
    photoFilename: "ashutosh-pande-senior-mathematics-faculty-rank-sarthi.webp",
    imageAlt: "Ashutosh Pande, Senior Mathematics Faculty at Rank Sarthi",
    initials: "AP",
    claimsRequiringEvidence: [
      "JEE 1998 qualification",
      "Degree and institution",
      "Student rank outcomes",
      "Teaching experience",
      "LinkedIn",
      "Professional email",
    ],
  },
  {
    id: "prabhat-kumar",
    education: "Chaudhary Charan Singh University",
    slug: "prabhat-kumar",
    name: "Prabhat Kumar",
    title: "Senior Chemistry Faculty",
    subject: "Chemistry",
    role: "Senior Chemistry Educator / Academic Contributor",
    shortProfile:
      "Prabhat Kumar is a Senior Chemistry Faculty member and academic author working in competitive-exam preparation and Chemistry curriculum development, with a focus on conceptual clarity, scientific accuracy and graded problem-solving.",
    detailedProfile: [
      "Prabhat Kumar is a senior Chemistry educator and curriculum contributor whose work focuses on conceptual rigour, scientific accuracy and graded competitive problem-solving.",
      "He has mentored students preparing for JEE and NEET, and his contribution to Chemistry learning runs through curriculum engineering, academic writing and the construction of structured learning resources.",
      "Curriculum engineering, in his work, means treating a syllabus as a dependency graph rather than a list: identifying which concepts must be secure before another can be taught honestly, and placing reinforcement where the dependency is strongest rather than where it is most convenient.",
      "His academic-writing contribution shows in the explanation layer. Chemistry explanations are written to be read once and understood, with terminology used consistently, standard results stated with their conditions, and worked examples chosen to expose the reasoning step rather than to demonstrate a finished answer.",
      "Graded problem-solving is the practice layer: sequences that begin with single-concept application, progress to problems combining two or more ideas, and end with the synthesis-type questions that competitive Chemistry uses to separate candidates.",
      "For Rank Sarthi, his positioning is senior Chemistry educator, academic author and curriculum contributor focused on conceptual rigour, scientific accuracy and graded competitive problem-solving.",
    ],
    academicFocus: [
      "Curriculum engineering and concept-dependency sequencing in Chemistry",
      "Academic writing with consistent terminology and stated conditions",
      "Graded competitive problem-solving from single-concept to synthesis level",
      "Conceptual rigour and scientific accuracy in JEE and NEET Chemistry",
    ],
    expertise: [
      "Chemistry",
      "JEE Chemistry",
      "NEET Chemistry",
      "Academic Publishing",
      "Curriculum Development",
      "Competitive Exam Preparation",
    ],
    examScope: ["JEE Chemistry", "NEET Chemistry"],
    contribution: [
      "Chemistry curriculum development and concept-dependency sequencing.",
      "Academic writing and explanation quality across Chemistry content.",
      "Graded Chemistry problem sequences for JEE and NEET preparation.",
    ],
    reviewAreas: ["Chemistry", "JEE Chemistry", "NEET Chemistry", "Curriculum Development", "Academic Writing"],
    relatedPages: ["/neet/syllabus/chemistry", "/neet/chemistry", "/jee/chemistry"],
    verificationStatus: partial,
    photo: "/faculty/prabhat-kumar-senior-chemistry-faculty-rank-sarthi.webp",
    photoFilename: "prabhat-kumar-senior-chemistry-faculty-rank-sarthi.webp",
    imageAlt: "Prabhat Kumar, Senior Chemistry Faculty at Rank Sarthi",
    initials: "PK",
    claimsRequiringEvidence: [
      "Years of experience",
      "Shri Balaji Publications ownership",
      "Authorship or publications",
      "Associated ventures",
      "Student outcomes",
      "LinkedIn",
      "Professional email",
    ],
  },
  {
    id: "hardik-agrawal",
    education: "Indian Institute of Technology Delhi",
    slug: "hardik-agrawal",
    name: "Hardik Agrawal",
    title: "Physics Expert",
    subject: "Physics",
    role: "Physics Expert",
    shortProfile:
      "Hardik Agrawal is a Physics Expert working across competitive Physics and digital learning systems. His academic contribution connects fundamental physical principles with structured mathematical application and multi-step problem-solving for JEE aspirants.",
    detailedProfile: [
      "Hardik Agrawal is a Physics Expert whose academic contribution connects abstract physical laws to structured mathematical application and multi-step problem-solving for JEE Main and JEE Advanced learners.",
      "His Physics work concentrates on the translation step that most competitive questions actually test: converting a described physical situation into a correct mathematical statement. Free-body reasoning, field and potential arguments, energy accounting and constraint relations are treated as the tools of that translation.",
      "Multi-step problem-solving follows from it. Advanced Physics problems typically chain two or three principles, and his content emphasises recognising which chain a problem requires, keeping the algebra controlled through the chain, and validating the result dimensionally and in limiting cases.",
      "He also works on the digital learning systems and learning architecture supporting Rank Sarthi — how content is structured, delivered and kept consistent at scale, including the presentation of mathematical notation and the organisation of interlinked academic material.",
      "For Rank Sarthi, his contribution combines competitive Physics reasoning with the educational-technology work that keeps that reasoning legible and consistent across the platform.",
    ],
    academicFocus: [
      "Translating physical situations into correct mathematical statements",
      "Multi-step JEE Physics problem chains and result validation",
      "Digital learning systems and academic content architecture",
      "Consistent mathematical notation and interlinked academic material",
    ],
    expertise: [
      "Physics",
      "JEE Physics",
      "Competitive Problem Solving",
      "Digital Learning Systems",
      "Educational Technology",
      "Platform Architecture",
    ],
    examScope: ["JEE Main Physics", "JEE Advanced Physics"],
    contribution: [
      "Structured mathematical application and multi-step problem work in JEE Physics content.",
      "Contribution to the digital learning systems and content architecture behind Rank Sarthi.",
      "Notation consistency and legibility of mathematical presentation across academic pages.",
    ],
    reviewAreas: ["Physics", "JEE Physics", "Competitive Problem Solving", "Digital Learning Systems"],
    relatedPages: ["/jee/syllabus/physics", "/jee/physics", "/jee/jee-advanced/syllabus"],
    verificationStatus: partial,
    photo: "/faculty/hardik-agrawal-physics-expert-rank-sarthi.webp",
    photoFilename: "hardik-agrawal-physics-expert-rank-sarthi.webp",
    imageAlt: "Hardik Agrawal, Physics Expert at Rank Sarthi",
    initials: "HA",
    claimsRequiringEvidence: [
      "Exact public technology title",
      "JEE Main result",
      "JEE Advanced result",
      "MVPP or JSTSE rank",
      "Technical responsibilities",
      "LinkedIn",
      "Professional email",
    ],
  },
];

const profilesBySlug = new Map(academicProfiles.map((profile) => [profile.slug, profile]));

export function getAcademicProfile(slug: string): AcademicProfile | undefined {
  return profilesBySlug.get(slug);
}

/** Internal subject suitability pools. Never rendered as page-level review evidence. */
export const reviewerPools: Record<AcademicSubject, string[]> = {
  Physics: ["gandharva-saxena", "ashwin-m", "hardik-agrawal"],
  Chemistry: ["adarsh-kumar", "vinod-kumar", "prabhat-kumar"],
  Mathematics: ["sachin-garg", "ashutosh-pande"],
};
