import type { FreshDataRecord, FreshnessChangeLogEntry } from "./types";

/**
 * Approved FreshDataRecords. Every entry here has passed the review gate:
 * `reviewStatus: "APPROVED"`. Nothing enters this file automatically — the
 * watcher writes change CANDIDATES, a human approves, only then does the
 * public value move.
 */
export const freshDataRecords: FreshDataRecord[] = [
  {
    id: "jee-main-2027-schedule-status",
    pageUrl: "/jee/exam-dates",
    platform: "JEE",
    exam: "JEE Main",
    cycle: "2027",
    field: "scheduleStatus",
    fieldLabel: "JEE Main 2027 schedule",
    currentValue: "Not officially announced",
    status: "NOT_ANNOUNCED",
    sourceRef: "NTA-HOME",
    sourceUrl: "https://jeemain.nta.nic.in/",
    sourceAuthority: "National Testing Agency",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "DAILY",
    refreshTrigger: ["new information bulletin", "new application notice", "schedule correction"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "SHOW_NOT_ANNOUNCED",
      publicMessage: "Official source could not be rechecked. No unverified date has been added.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-advanced-2027-schedule-status",
    pageUrl: "/jee/exam-dates",
    platform: "JEE",
    exam: "JEE Advanced",
    cycle: "2027",
    field: "scheduleStatus",
    fieldLabel: "JEE Advanced 2027 schedule",
    currentValue: "Not officially announced",
    status: "NOT_ANNOUNCED",
    sourceRef: "ADV-HOME-2026",
    sourceUrl: "https://jeeadv.ac.in/",
    sourceAuthority: "JEE Advanced official organising authority",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "DAILY",
    refreshTrigger: ["new organising site", "examination date", "information brochure"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "SHOW_NOT_ANNOUNCED",
      publicMessage: "Official source could not be rechecked. No unverified date has been added.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-main-2026-s2-p1-final-key",
    pageUrl: "/jee/answer-key",
    platform: "JEE",
    exam: "JEE Main",
    cycle: "2026",
    field: "answerKeyState",
    fieldLabel: "JEE Main 2026 Session 2 Paper 1 answer key",
    currentValue: "Final answer key available for Session 2 Paper 1",
    status: "VERIFIED",
    sourceRef: "NTA-FINAL-KEY-S2-P1-2026",
    sourceUrl:
      "https://cdnbbsr.s3waas.gov.in/s3f8e59f4b2fe7c5705bf878bbd494ccdf/uploads/2026/04/20260420409057044.pdf",
    sourceAuthority: "National Testing Agency",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["revised key", "withdrawal", "official URL change"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Last verified final key retained; official file could not be rechecked.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-advanced-2026-final-keys",
    pageUrl: "/jee/answer-key",
    platform: "JEE",
    exam: "JEE Advanced",
    cycle: "2026",
    field: "answerKeyState",
    fieldLabel: "JEE Advanced 2026 final answer keys",
    currentValue: "Final answer keys available for Paper 1 and Paper 2",
    status: "VERIFIED",
    sourceRef: "ADV-HOME-2026",
    sourceUrl: "https://jeeadv.ac.in/",
    sourceAuthority: "JEE Advanced 2026 organising authority, IIT Roorkee",
    publishedAt: "2026-06-01T14:45:00+05:30",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["revised key", "withdrawal", "official URL change"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Last verified final-key status retained; check the official authority before acting.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-advanced-2026-crl-qualifying-marks",
    pageUrl: "/jee/cutoff",
    platform: "JEE",
    exam: "JEE Advanced",
    cycle: "2026",
    field: "qualifyingMarks.commonRankList",
    fieldLabel: "JEE Advanced 2026 Common Rank List qualifying marks",
    currentValue: { minimumEachSubject: 8, minimumAggregate: 92 },
    status: "VERIFIED",
    sourceRef: "ADV-CUTOFF-2026",
    sourceUrl: "https://jeeadv.ac.in/documents/cutoffs_2026.pdf",
    sourceAuthority: "JEE Advanced 2026 organising authority",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["corrected qualifying marks", "replacement PDF"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Last verified 2026 table retained; official source recheck is pending.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-2026-rank-sarthi-analysis-status",
    pageUrl: "/jee/analysis",
    platform: "JEE",
    exam: "JEE Main and JEE Advanced",
    cycle: "2026",
    field: "rankSarthiAnalysisStatus",
    fieldLabel: "Rank Sarthi analysis readiness",
    currentValue: "No approved analysed dataset supplied",
    status: "VERIFIED",
    sourceRef: "INTERNAL-DATASET-REGISTER",
    sourceUrl: "https://ranksarthi.com/jee/analysis",
    sourceAuthority: "Rank Sarthi editorial control",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "EVENT_TRIGGERED",
    refreshTrigger: ["approved dataset created", "dataset corrected", "dataset withdrawn"],
    confidence: "HIGH",
    changePolicy: "NEVER_AUTO_PUBLISH",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Analysis remains unavailable until a reviewed dataset exists.",
      actionState: "HIDE",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
];

/**
 * Visible "What changed" entries. Empty by design: no approved post-baseline
 * factual change has passed the review gate. Daily no-change checks, parser
 * repairs and health checks never create an entry here.
 */
export const freshnessChangeLog: FreshnessChangeLogEntry[] = [];
