/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlatformIndexRouteImport } from './routes/$platform.index'
import { Route as PlatformSyllabusRouteImport } from './routes/$platform.syllabus'
import { Route as PlatformSubjectChapterRouteImport } from './routes/$platform.$subject.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/$platform/',
  path: '/$platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSyllabusRoute = PlatformSyllabusRouteImport.update({
  id: '/$platform/syllabus',
  path: '/$platform/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSubjectChapterRoute = PlatformSubjectChapterRouteImport.update({
  id: '/$platform/$subject/$chapter',
  path: '/$platform/$subject/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$platform/syllabus': typeof PlatformSyllabusRoute
  '/$platform/': typeof PlatformIndexRoute
  '/$platform/$subject/$chapter': typeof PlatformSubjectChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$platform/syllabus': typeof PlatformSyllabusRoute
  '/$platform': typeof PlatformIndexRoute
  '/$platform/$subject/$chapter': typeof PlatformSubjectChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$platform/syllabus': typeof PlatformSyllabusRoute
  '/$platform/': typeof PlatformIndexRoute
  '/$platform/$subject/$chapter': typeof PlatformSubjectChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/$platform/syllabus'
    | '/$platform/'
    | '/$platform/$subject/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$platform/syllabus'
    | '/$platform'
    | '/$platform/$subject/$chapter'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/$platform/syllabus'
    | '/$platform/'
    | '/$platform/$subject/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PlatformSyllabusRoute: typeof PlatformSyllabusRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformSubjectChapterRoute: typeof PlatformSubjectChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$platform/': {
      id: '/$platform/'
      path: '/$platform'
      fullPath: '/$platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$platform/syllabus': {
      id: '/$platform/syllabus'
      path: '/$platform/syllabus'
      fullPath: '/$platform/syllabus'
      preLoaderRoute: typeof PlatformSyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$platform/$subject/$chapter': {
      id: '/$platform/$subject/$chapter'
      path: '/$platform/$subject/$chapter'
      fullPath: '/$platform/$subject/$chapter'
      preLoaderRoute: typeof PlatformSubjectChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PlatformSyllabusRoute: PlatformSyllabusRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformSubjectChapterRoute: PlatformSubjectChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
